# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
