# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
